Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 27.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
#En esta url va nuestra base de datos (En este caso en render)
database_url = "postgresql://etl_seguros_fwgm_user:FLIwCR2BnSl9vmgdqKd7GtpzOyBHRpyl@dpg-d6qu5hk50q8c73bpe0p0-a.oregon-postgres.render.com/etl_seguros_fwgm"
engine = create_engine(database_url)

Cargar Dataset

In [76]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline-25-1449-2022/refs/heads/main/data/raw/B_proveedores.csv"
proveedores = pd.read_csv(url)

Exploración de datos

In [77]:
proveedores.head()

  id_proveedor              proveedor         pais
0         P300             SurtiMax 0    Guatemala
1         P301     Insumos Globales 1   Costa Rica
2         P302  Distribuidora Atlas 2  El Salvador
3         P303          TecnoSupply 3    Guatemala
4         P304     Insumos Globales 4    Guatemala

In [78]:
proveedores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_proveedor  38 non-null     object
 1   proveedor     38 non-null     object
 2   pais          38 non-null     object
dtypes: object(3)
memory usage: 1.0+ KB

In [80]:
proveedores.isnull().sum()

id_proveedor    0
proveedor       0
pais            0
dtype: int64

In [85]:
proveedores.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [82]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [83]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [84]:
proveedores = normalizar_columnas(proveedores)
proveedores = limpiar_texto(proveedores)
proveedores = proveedores.drop_duplicates()

Funciones especificas

In [89]:
#Normalizar pais

map_pais = {
    "EL SALVADOR": "El Salvador",
    "el salvador": "El Salvador",
    "El Salvador": "El Salvador",

    "GUATEMALA": "Guatemala",
    "guatemala": "Guatemala",
    "Guatemala": "Guatemala",

    "COSTA RICA": "Costa Rica",
    "costa rica": "Costa Rica",
    "Costa Rica": "Costa Rica",

    "HONDURAS": "Honduras",
    "honduras": "Honduras",
    "Honduras": "Honduras"
}


#Limpiar a los proveedores

proveedores["proveedor"] = proveedores["proveedor"].str.replace(r'\s\d+$',"",regex=True)

In [88]:
proveedores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_proveedor  35 non-null     object
 1   proveedor     35 non-null     object
 2   pais          35 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB

In [87]:
proveedores.head()

  id_proveedor            proveedor         pais
0         P300             SurtiMax    Guatemala
1         P301     Insumos Globales   Costa Rica
2         P302  Distribuidora Atlas  El Salvador
3         P303          TecnoSupply    Guatemala
4         P304     Insumos Globales    Guatemala

Separar validos y rechazados

In [90]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. el proveedor no puede ser nulo ni estar vacio

columnas_obligatorias = [
    "id_proveedor",
    "proveedor"
]

condicion_nulos = proveedores[columnas_obligatorias].isna().any(axis=1)

rechazados = proveedores.loc[condicion_nulos].copy()
validos = proveedores.loc[~condicion_nulos].copy()

Motivo del rechazo

In [91]:
from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_proveedor"]):
    motivos.append("ID_proveedor_no_valido")

  if pd.isna(row["proveedor"]):
    motivos.append("proveedor_no_valido")

  return ",".join(motivos)

Agregar motivo de rechazo

In [92]:
rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar Archivos

In [93]:
validos.to_csv("proveedores_curated.csv", index=False)
rechazados.to_csv("proveedores_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [94]:
validos.head()

  id_proveedor            proveedor         pais
0         P300             SurtiMax    Guatemala
1         P301     Insumos Globales   Costa Rica
2         P302  Distribuidora Atlas  El Salvador
3         P303          TecnoSupply    Guatemala
4         P304     Insumos Globales    Guatemala

In [95]:
validos.dtypes

id_proveedor    object
proveedor       object
pais            object
dtype: object

In [96]:
validos.isnull().sum()

id_proveedor    0
proveedor       0
pais            0
dtype: int64

In [97]:
proveedores.value_counts()

id_proveedor  proveedor            pais
P300          SurtiMax             Guatemala      1
P301          Insumos Globales     Costa Rica     1
P302          Distribuidora Atlas  El Salvador    1
P303          TecnoSupply          Guatemala      1
P304          Insumos Globales     Guatemala      1
P305          TecnoSupply          El Salvador    1
P306           CompuRed 6          El Salvador    1
P307          OfiMarket            El Salvador    1
P308          Papelera Unión       Guatemala      1
P309          CompuRed             Guatemala      1
P310          TecnoSupply          Costa Rica     1
P311          Insumos Globales     Honduras       1
P312          SurtiMax             El Salvador    1
P313          TecnoSupply          Guatemala      1
P314          Insumos Globales     Guatemala      1
P315          Mayorista Centro     El Salvador    1
P316          LogiParts            Honduras       1
P317          Distribuidora Atlas  El Salvador    1
P318          Distribuidora Atlas  Honduras       1
P319          ElectroPro           Guatemala      1
P320          ElectroPro           Honduras       1
P321          CompuRed             Costa Rica     1
P322          LogiParts            Guatemala      1
P323          Papelera Unión       Costa Rica     1
P324          Distribuidora Atlas  El Salvador    1
P325          ElectroPro 25        El Salvador    1
P326          LogiParts            El Salvador    1
P327           OfiMarket 27        Honduras       1
P328          Papelera Unión       Guatemala      1
P329          TecnoSupply          El Salvador    1
P330           LogiParts 30        El Salvador    1
P331          SurtiMax             Guatemala      1
P332          ElectroPro           El Salvador    1
P333          TecnoSupply          Costa Rica     1
P334          TecnoSupply          Guatemala      1
Name: count, dtype: int64

In [98]:
validos.to_sql(
    "proveedores",
    engine,
    if_exists="append",
    index=False
  )

35

Validar Carga

In [99]:
pd.read_sql(
    "Select * From proveedores Limit 100",
    engine
)

   id_proveedor            proveedor         pais
0          P300             SurtiMax    Guatemala
1          P301     Insumos Globales   Costa Rica
2          P302  Distribuidora Atlas  El Salvador
3          P303          TecnoSupply    Guatemala
4          P304     Insumos Globales    Guatemala
5          P305          TecnoSupply  El Salvador
6          P306          CompuRed 6   El Salvador
7          P307            OfiMarket  El Salvador
8          P308       Papelera Unión    Guatemala
9          P309             CompuRed    Guatemala
10         P310          TecnoSupply   Costa Rica
11         P311     Insumos Globales     Honduras
12         P312             SurtiMax  El Salvador
13         P313          TecnoSupply    Guatemala
14         P314     Insumos Globales    Guatemala
15         P315     Mayorista Centro  El Salvador
16         P316            LogiParts     Honduras
17         P317  Distribuidora Atlas  El Salvador
18         P318  Distribuidora Atlas     Honduras
19         P319           ElectroPro    Guatemala
20         P320           ElectroPro     Honduras
21         P321             CompuRed   Costa Rica
22         P322            LogiParts    Guatemala
23         P323       Papelera Unión   Costa Rica
24         P324  Distribuidora Atlas  El Salvador
25         P325       ElectroPro 25   El Salvador
26         P326            LogiParts  El Salvador
27         P327        OfiMarket 27      Honduras
28         P328       Papelera Unión    Guatemala
29         P329          TecnoSupply  El Salvador
30         P330        LogiParts 30   El Salvador
31         P331             SurtiMax    Guatemala
32         P332           ElectroPro  El Salvador
33         P333          TecnoSupply   Costa Rica
34         P334          TecnoSupply    Guatemala